### ISSUE TITLE
Deprecated constructing a TreeBuilder without passing root node information

### ISSUE THREAD

**Issue by heximcz** [php-translation/symfony-bundle#307] opened 2019-05-30 14:08 UTC
```
A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.

The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "translation" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.
Hide context    Hide trace
[▼
  "exception" => SilencedErrorContext^ {#1420 ▶}
]
{▼
  .../vendor/symfony/config/Definition/Builder/TreeBuilder.php:52 {▶}
 .../vendor/php-translation/symfony-bundle/DependencyInjection/Configuration.php:37 {▼
    › $treeBuilder = new TreeBuilder();
    › $root = $treeBuilder->root('translation');
    › 
  }
}
```

Solution is here:
https://github.com/symfony/symfony/blob/master/UPGRADE-4.2.md#config

**Comment by bocharsky-bw** [comment] 2019-05-31 08:04
Duplicate of #275

It was fixed in #273 , though there's no release for this yet. I think you can track the progress here: #287

**Closed by bocharsky-bw** 2019-05-31 08:04 UTC
